/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppWewRouteImport } from './routes/_app/wew'
import { Route as AppTagsIndexRouteImport } from './routes/_app/tags/index'
import { Route as AppStarIndexRouteImport } from './routes/_app/star/index'
import { Route as AppRecentIndexRouteImport } from './routes/_app/recent/index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections/index'
import { Route as AppBookmarksIndexRouteImport } from './routes/_app/bookmarks/index'
import { Route as AppArchiveIndexRouteImport } from './routes/_app/archive/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWewRoute = AppWewRouteImport.update({
  id: '/wew',
  path: '/wew',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsIndexRoute = AppTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStarIndexRoute = AppStarIndexRouteImport.update({
  id: '/star/',
  path: '/star/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecentIndexRoute = AppRecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookmarksIndexRoute = AppBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchiveIndexRoute = AppArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/wew': typeof AppWewRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/archive/': typeof AppArchiveIndexRoute
  '/bookmarks/': typeof AppBookmarksIndexRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/recent/': typeof AppRecentIndexRoute
  '/star/': typeof AppStarIndexRoute
  '/tags/': typeof AppTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/wew': typeof AppWewRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/archive': typeof AppArchiveIndexRoute
  '/bookmarks': typeof AppBookmarksIndexRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/recent': typeof AppRecentIndexRoute
  '/star': typeof AppStarIndexRoute
  '/tags': typeof AppTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/_app/wew': typeof AppWewRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/archive/': typeof AppArchiveIndexRoute
  '/_app/bookmarks/': typeof AppBookmarksIndexRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/recent/': typeof AppRecentIndexRoute
  '/_app/star/': typeof AppStarIndexRoute
  '/_app/tags/': typeof AppTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/wew'
    | '/sign-in'
    | '/sign-up'
    | '/archive/'
    | '/bookmarks/'
    | '/collections/'
    | '/recent/'
    | '/star/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/wew'
    | '/sign-in'
    | '/sign-up'
    | '/archive'
    | '/bookmarks'
    | '/collections'
    | '/recent'
    | '/star'
    | '/tags'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/dashboard'
    | '/todos'
    | '/_app/wew'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/archive/'
    | '/_app/bookmarks/'
    | '/_app/collections/'
    | '/_app/recent/'
    | '/_app/star/'
    | '/_app/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/wew': {
      id: '/_app/wew'
      path: '/wew'
      fullPath: '/wew'
      preLoaderRoute: typeof AppWewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tags/': {
      id: '/_app/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppTagsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/star/': {
      id: '/_app/star/'
      path: '/star'
      fullPath: '/star/'
      preLoaderRoute: typeof AppStarIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/recent/': {
      id: '/_app/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof AppRecentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bookmarks/': {
      id: '/_app/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof AppBookmarksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/archive/': {
      id: '/_app/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof AppArchiveIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppWewRoute: typeof AppWewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArchiveIndexRoute: typeof AppArchiveIndexRoute
  AppBookmarksIndexRoute: typeof AppBookmarksIndexRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppRecentIndexRoute: typeof AppRecentIndexRoute
  AppStarIndexRoute: typeof AppStarIndexRoute
  AppTagsIndexRoute: typeof AppTagsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWewRoute: AppWewRoute,
  AppIndexRoute: AppIndexRoute,
  AppArchiveIndexRoute: AppArchiveIndexRoute,
  AppBookmarksIndexRoute: AppBookmarksIndexRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppRecentIndexRoute: AppRecentIndexRoute,
  AppStarIndexRoute: AppStarIndexRoute,
  AppTagsIndexRoute: AppTagsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
